class GuideGenerator:
    """플래너의 JSON 결과를 사람이 읽기 쉬운 가이드 문서로 변환합니다."""
    
    @staticmethod
    def generate_markdown(body_name, strategy, plans):
        lines = []
        lines.append(f"# Decomposition Guide: {body_name}")
        lines.append(f"**Strategy Selected:** {strategy}")
        lines.append("\n## Step-by-Step Instructions")
        
        for i, plan in enumerate(plans):
            lines.append(f"### [Step {i+1}] {plan['strategy']} Operation")
            
            if plan['strategy'] == "AXIAL":
                lines.append(f"- **Action:** Split the body horizontally at **Z = {plan['core_offset']:.2f}mm**.")
                lines.append(f"- **Target:** Apply to all current descendants of the main body.")
                
            elif plan['strategy'] == "SECTOR":
                lines.append(f"- **Action:** Perform a cross-split (X and Y axis) through the center.")
                lines.append(f"- **Angle:** 90-degree increments.")
                lines.append(f"- **Purpose:** To create 4 manageable quadrants for high-quality mesh.")
                
            elif plan['strategy'] == "OGRID":
                lines.append(f"- **Action:** Extract/Offset a circular core with offset **{plan.get('core_offset', 2.0):.2f}mm**.")
                lines.append(f"- **Location:** Center of the cylinder axis.")
                lines.append(f"- **Named Selection:** {plan.get('named_selections', {}).get('core', 'CORE')}")

            elif plan['strategy'] == "JUNCTION_CORE":
                lines.append("- **Action:** Isolate the intersection core block.")
                lines.append("- **Purpose:** To capture stress concentrations at the pipe junction using a hexa-core.")

            elif plan['strategy'] == "HGRID":
                lines.append("- **Action:** Perform planar grid splitting for the block body.")
                lines.append("- **Purpose:** To maintain orthogonal mesh quality for non-cylindrical regions.")
            
            lines.append("")
            
        lines.append("\n---")
        lines.append("*Generated by AntiGravity Solid Decomposer*")
        
        return "\n".join(lines)

if __name__ == "__main__":
    # 예시 실행
    sample_plans = [
        {"strategy": "AXIAL", "core_offset": 50.0},
        {"strategy": "SECTOR", "core_offset": 0.0}
    ]
    guide = GuideGenerator.generate_markdown("LV11_VALVE_BODY", "AXISYMMETRIC", sample_plans)
    
    guide_path = "scdm_bridge/Decomposition_Guide_Sample.md"
    with open(guide_path, "w", encoding="utf-8") as f:
        f.write(guide)
    print(f"Sample Guide generated at: {guide_path}")
