class GuideGenerator:
    """플래너의 JSON 결과를 사람이 읽기 쉬운 가이드 문서로 변환합니다."""
    
    @staticmethod
    def generate_markdown(body_name, strategy, plans):
        lines = []
        lines.append(f"# Decomposition Guide: {body_name}")
        lines.append(f"**Strategy Selected:** {strategy}")
        lines.append("\n## Step-by-Step Instructions")
        
        if not plans:
            lines.append("*No specific steps generated for this body.*")
            return "\n".join(lines)
            
        for i, plan in enumerate(plans):
            s_type = plan.get('strategy', 'Unknown')
            lines.append(f"### [Step {i+1}] {s_type} Operation")
            
            if s_type == "AXIAL":
                origin = plan.get('split_plane', {}).get('origin', [0,0,0])
                lines.append(f"- **Action:** Split the body at **Z = {origin[2]:.2f}mm**.")
                lines.append("- **Purpose:** To isolate features along the axis.")
                
            elif s_type == "SECTOR":
                lines.append("- **Action:** Perform a 90-degree radial cross-split.")
                lines.append("- **Purpose:** To create mappable quadrants.")
                
            elif s_type == "OGRID":
                offset = plan.get('core_offset', 2.0)
                lines.append(f"- **Action:** Create a central O-grid core with offset **{offset:.2f}mm**.")
                lines.append("- **Status:** Essential for butterfly mesh quality.")

            elif s_type == "TRANSVERSE":
                lines.append("- **Action:** Cut the pipe perpendicular to its axis at the junction.")
            
            else:
                lines.append(f"- **Action:** Specialized decomposition step ({s_type}).")
            
            lines.append("")
            
        lines.append("\n---")
        lines.append("*Generated by AntiGravity Solid Decomposer (v2.2)*")
        
        return "\n".join(lines)
