class GuideGenerator:
    """플래너의 JSON 결과를 사람이 읽기 쉬운 가이드 문서로 변환합니다."""
    
    @staticmethod
    def generate_markdown(body_name, strategy, plans):
        lines = []
        lines.append(f"# Decomposition Guide: {body_name}")
        lines.append(f"**Overall Strategy:** {strategy}")
        lines.append("\n## Step-by-Step Instructions")
        
        if not plans:
            lines.append("*No specific steps were generated for this body.*")
            return "\n".join(lines)
            
        for i, plan in enumerate(plans):
            # 전략 이름 정규화
            raw_strat = str(plan.get('strategy', 'UNKNOWN')).upper()
            lines.append(f"### [Step {i+1}] {raw_strat} Operation")
            
            # 1. O-GRID (원통형 코어 분할)
            if "OGRID" in raw_strat:
                offset = plan.get('core_offset', 2.0)
                if offset is None: offset = 2.0
                lines.append(f"- **Action:** Create a circular O-grid core (offset: **{offset:.2f}mm**).")
                lines.append("- **Purpose:** Ensures high-quality hexa-mesh in the center of cylinders.")
            
            # 2. AXIAL (축방향 단차 분할)
            elif "AXIAL" in raw_strat:
                origin = plan.get('split_plane', {}).get('origin', [0,0,0])
                z_val = origin[2] if len(origin) > 2 else 0.0
                lines.append(f"- **Action:** Split the body horizontally at **Z = {z_val:.2f}mm**.")
                lines.append("- **Purpose:** Isolate features or handle step changes in diameter.")

            # 3. SECTOR (90도 방사형 분할)
            elif "SECTOR" in raw_strat:
                lines.append("- **Action:** Perform a 90-degree radial cross-split.")
                lines.append("- **Purpose:** Create manageable quadrants for standard meshing.")

            # 4. HGRID (박스형 평면 분할)
            elif "HGRID" in raw_strat:
                lines.append("- **Action:** Apply orthogonal planar splits to the block-based body.")
                lines.append("- **Purpose:** Maintain grid alignment for rectangular features.")

            # 5. TRANSVERSE / JUNCTION (교차로/굽힘 분할)
            elif "TRANSVERSE" in raw_strat or "JUNCTION" in raw_strat:
                lines.append("- **Action:** Perform transverse cuts at the pipe junction or elbow.")
                lines.append("- **Purpose:** Isolate the complex intersection zone.")

            # 6. Fallback (기타 정의되지 않은 모든 경우)
            else:
                lines.append(f"- **Action:** Execute specialized decomposition ({raw_strat}).")
                lines.append("- **Purpose:** Simplify geometry for structured meshing.")
            
            lines.append("")
            
        lines.append("\n---")
        lines.append("*Generated by AntiGravity Solid Decomposer (v2.4)*")
        
        return "\n".join(lines)
