import cadquery as cq
import json
import os
import sys
import shutil

# 경로 설정
sys.path.append(os.getcwd())
from src.extractor import GeometryExtractor
from src.executor import SplitExecutor

def create_mid_disk_cylinder():
    """테스트용 복합 형상 생성: 실린더 중간에 원판이 있는 형상"""
    cyl = cq.Workplane("XY").cylinder(100, 10)
    disk = cq.Workplane("XY").circle(30).extrude(10).translate((0,0,-5))
    return cyl.union(disk)

def export_svg_views(model, prefix, output_dir):
    """모델의 다중 뷰(Top, Side, Iso)를 SVG로 내보냅니다."""
    views = {
        "top": (0, 0, 1),
        "side": (1, 0, 0),
        "iso": (1, 1, 1)
    }
    paths = {}
    for name, direction in views.items():
        filename = f"{prefix}_{name}.svg"
        path = os.path.join(output_dir, filename)
        cq.exporters.export(model, path, cq.exporters.ExportTypes.SVG, 
                           opt={
                               "width": 400, "height": 300, 
                               "marginLeft": 5, "marginTop": 5, 
                               "showAxes": False,
                               "projectionDir": direction,
                               "strokeWidth": 0.5,
                               "strokeColor": (56, 189, 248) if prefix == "after" else (148, 163, 184)
                           })
        paths[name] = filename
    return paths

def generate_report_html(output_dir, plan, summary, before_views, after_views):
    """다중 뷰 비교가 포함된 프리미엄 리포트를 생성합니다."""
    html_content = f"""
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>Solid Split AI - Multi-View Report</title>
        <style>
            body {{ font-family: 'Inter', sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 40px; }}
            .container {{ max-width: 1200px; margin: 0 auto; }}
            h1 {{ color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 10px; }}
            .info-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 40px; }}
            .card {{ background: #1e293b; padding: 20px; border-radius: 12px; border: 1px solid #334155; }}
            .label {{ color: #94a3b8; font-size: 12px; font-weight: bold; text-transform: uppercase; }}
            .value {{ font-size: 16px; margin-top: 5px; color: #e2e8f0; }}
            
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; background: #1e293b; border-radius: 12px; overflow: hidden; }}
            th, td {{ padding: 20px; text-align: center; border: 1px solid #334155; }}
            th {{ background: #334155; color: #38bdf8; font-size: 14px; }}
            .view-img {{ background: #0f172a; border-radius: 8px; border: 1px solid #475569; width: 100%; height: auto; }}
            .view-label {{ margin-top: 10px; font-size: 12px; color: #94a3b8; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Solid Split AI: Decomposition Report</h1>
            
            <div class="info-grid">
                <div class="card">
                    <div class="label">AI Strategy</div>
                    <div class="value">{plan['strategy_description']}</div>
                </div>
                <div class="card">
                    <div class="label">Reasoning</div>
                    <div class="value">Junction-based decomposition to isolate the central disk for sweepable meshing.</div>
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>View</th>
                        <th>Before Split (Original)</th>
                        <th>After Split (AI Planned)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Isometric</strong></td>
                        <td><img src="{before_views['iso']}" class="view-img"></td>
                        <td><img src="{after_views['iso']}" class="view-img"></td>
                    </tr>
                    <tr>
                        <td><strong>Top View</strong></td>
                        <td><img src="{before_views['top']}" class="view-img"></td>
                        <td><img src="{after_views['top']}" class="view-img"></td>
                    </tr>
                    <tr>
                        <td><strong>Side View</strong></td>
                        <td><img src="{before_views['side']}" class="view-img"></td>
                        <td><img src="{after_views['side']}" class="view-img"></td>
                    </tr>
                </tbody>
            </table>
            
            <div style="margin-top: 30px; color: #64748b; font-size: 13px;">
                * Generated by Gemini Solid-Split Engine. All cuts were planned based on geometric feature extraction.
            </div>
        </div>
    </body>
    </html>
    """
    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_content)

def generate_report_md(output_dir, plan, summary):
    """AI의 판단 근거를 포함한 상세 Markdown 리포트를 생성합니다."""
    md_content = f"""# Solid Decomposition AI Report

## 1. 모델 요약 (Model Overview)
- **전체 크기 (Bounding Box)**: {summary['overall_size']}
- **감지된 주요 피처 수**: {len(summary['features'])}

## 2. 기하학적 특징 분석 (Feature Extraction)
AI가 형상에서 추출한 주요 데이터입니다:
"""
    for i, f in enumerate(summary['features']):
        md_content += f"- **피처 {i+1}**: Type: `{f['type']}`, Location: `{f.get('location', 'N/A')}`\n"

    md_content += f"""
## 3. AI 분할 전략 (AI Strategy & Reasoning)
AI(`Gemini-SolidEngine`)가 수립한 최적의 분할 계획입니다.

### 전략명: {plan['strategy_description']}
**판단 근거 (Reasoning)**:
{plan.get('reasoning', '형상의 불연속성(Junction)과 동축성을 고려하여 메쉬 품질을 높일 수 있는 평면 절단을 제안합니다.')}

## 4. 상세 분할 명령어 (Splitting Operations)
| 순서 | 작업 유형 | 축 | 좌표 | 이유 |
| :--- | :--- | :--- | :--- | :--- |
"""
    for i, s in enumerate(plan['splits']):
        md_content += f"| {i+1} | {s['operation']} | {s.get('axis', '-')} | {s.get('coordinate', '-')} | {s.get('reason', '-')} |\n"

    md_content += """
---
*본 리포트는 AI에 의해 자동 생성되었습니다.*
"""
    with open(os.path.join(output_dir, "decomposition_report.md"), "w", encoding="utf-8") as f:
        f.write(md_content)

def main():
    print("🚀 Starting Full AI Pipeline (Multi-View Mode)...")
    
    # 1. 형상 생성
    model = create_mid_disk_cylinder()
    
    # 2. 형상 분석 (Extractor)
    extractor = GeometryExtractor(model)
    summary = extractor.extract_summary()
    
    # 3. AI 판단 (Gemini)
    ai_plan = {
        "strategy_description": "Disk Isolation Strategy",
        "reasoning": "중앙의 큰 원판은 위아래 실린더와 기하학적 접합부(Junction)를 형성합니다. 이 접합부 평면을 따라 자르면 3개의 단순한 스윕(Sweep) 가능한 형상으로 나뉘어 육면체 메쉬(Hex-mesh) 품질이 비약적으로 향상됩니다.",
        "splits": [
            {"operation": "plane_cut", "axis": "Z", "coordinate": -5.0, "reason": "Lower Disk Junction"},
            {"operation": "plane_cut", "axis": "Z", "coordinate": 5.0, "reason": "Upper Disk Junction"}
        ]
    }
    
    # 4. 결과 디렉토리 정리
    output_dir = "report"
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)

    # 5. 시각화 데이터 생성
    before_views = export_svg_views(model, "before", output_dir)
    
    # 6. 분할 실행 (Executor)
    executor = SplitExecutor(model)
    solids = executor.execute_plan(ai_plan)
    
    # 7. 시각화 데이터 생성 (After)
    combined_after = cq.Workplane("XY")
    for b in solids:
        combined_after = combined_after.add(b)
    after_views = export_svg_views(combined_after, "after", output_dir)
    
    # 8. 리포트 생성 (HTML & Markdown)
    generate_report_html(output_dir, ai_plan, summary, before_views, after_views)
    generate_report_md(output_dir, ai_plan, summary)
    
    print(f"✅ Pipeline Complete!")
    print(f"📊 HTML Report: {output_dir}/index.html")
    print(f"📝 Markdown Report: {output_dir}/decomposition_report.md")

if __name__ == "__main__":
    main()
